# SPDX-FileCopyrightText: 2022 - 2024 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

name: CI-openmp-macos-clang

on:
  push:
    branches: [ main ]
    paths-ignore: ['*-linux-gcc.yml', '*-windows-clang-cl.yml', '*-windows-msvc.yml']
    
  pull_request:
    branches: [ main ]
    paths-ignore: ['*-linux-gcc.yml', '*-windows-clang-cl.yml', '*-windows-msvc.yml']
    
  
jobs:
  macos:
    name: ${{ matrix.os }} (clang) (${{matrix.library_type}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        library_type: [shared, static]
        llvm: [llvm@18, llvm@19]                    
        os: [macos-15]
      
    steps:
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: false

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: super-ci-mac  # name for the cache
        
    # install clang
    - run: brew install coreutils ${{ matrix.llvm }}

    # install libomp
    - run: brew install libomp
    
    - run: pip install meson meson-python ninja pytest numpy

    - name: configure meson
      run: |
        CXX=$(brew --prefix ${{ matrix.llvm }})/bin/clang++  \
        LDFLAGS="-L/opt/homebrew/opt/libomp/lib" \
        CPPFLAGS="-I/opt/homebrew/opt/libomp/include" \
        meson setup builddir/ --default-library=${{matrix.library_type}} -Dpython.install_env=auto

    - name: compile project
      run: meson compile -C builddir/

    - name: test (cpp)
      run: meson test -C builddir/ --print-errorlogs

    - name: install project
      run: sudo meson install -C builddir/

    - name: test (pytest)
      run: pytest -v
