# SPDX-FileCopyrightText: 2022 - 2024 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

name: CI-openmp-macos-clang

on:
  push:
    branches: [ main ]
    paths-ignore: ['*-linux-gcc.yml', '*-windows-clang-cl.yml', '*-windows-msvc.yml']
    
  pull_request:
    branches: [ main ]
    paths-ignore: ['*-linux-gcc.yml', '*-windows-clang-cl.yml', '*-windows-msvc.yml']
    
  
jobs:
  macos:
    name: ${{ matrix.os }} (clang) (${{matrix.library_type}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        library_type: [shared, static]
        cxx_compiler: ["$(brew --prefix llvm@18)/bin/clang++"] 
        llvm: ["$(brew --prefix llvm@18)"]
        boost: ["$(brew --prefix boost)"]
        libomp: ["$(brew --prefix libomp)"]         
        os: [macos-14, macos-12]
    
    # env does not work here because is resolved as string and not command 
    # env:
    #   CXX: ${{ matrix.cxx_compiler }}
      
    steps:
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: checkout main repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: false

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: super-ci-mac  # name for the cache
        
    # install clang 18
    - run: brew install coreutils llvm@18

    # install libomp
    - run: brew install libomp
            
    - run: pip install meson ninja pytest

    - name: install custom meson
      run: |
        git clone https://github.com/mesonbuild/meson.git; cd meson; pip install .; meson --version
        # git clone https://github.com/peter-urban/meson.git; cd meson; git checkout fix-openmp-dependency-for-clang-cl; pip install .; meson --version
    
    - name: configure meson
      run: CXX=${{ matrix.llvm }}/bin/clang++  LDFLAGS="-L${{ matrix.llvm }}/lib/c++ -L${{ matrix.llvm }}/lib -undefined dynamic_lookup -Wl,-no_fixup_chains -Wl,-dead_strip -Wl,-rpath, ${{ matrix.llvm }}/lib/c++" CPPFLAGS="-I${{ matrix.llvm }}/include" meson setup builddir/ --default-library=${{matrix.library_type}} -D"python.install_env=auto"
      
    - name: compile project
      run: meson compile -C builddir/

    - name: test (cpp)
      run: meson test -C builddir/ --print-errorlogs

    - name: install project
      run: sudo meson install -C builddir/

    - name: test (pytest)
      run: pytest -v
